set(_CATKIN_CURRENT_PACKAGE "autonomos_gazebo")
set(autonomos_gazebo_VERSION "0.1.0")
set(autonomos_gazebo_MAINTAINER "Gary <gary.granados@gmail.com>")
set(autonomos_gazebo_PACKAGE_FORMAT "1")
set(autonomos_gazebo_BUILD_DEPENDS "dynamic_reconfigure" "eigen" "nodelet" "nodelet_topic_tools" "libpcl-all-dev" "pcl_conversions" "pcl_msgs" "pluginlib" "rosbag" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(autonomos_gazebo_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "eigen" "message_filters" "nodelet" "nodelet_topic_tools" "libpcl-all" "libpcl-all-dev" "pcl_conversions" "pcl_msgs" "pluginlib" "rosbag" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(autonomos_gazebo_BUILDTOOL_DEPENDS "catkin")
set(autonomos_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(autonomos_gazebo_EXEC_DEPENDS "dynamic_reconfigure" "eigen" "message_filters" "nodelet" "nodelet_topic_tools" "libpcl-all" "libpcl-all-dev" "pcl_conversions" "pcl_msgs" "pluginlib" "rosbag" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(autonomos_gazebo_RUN_DEPENDS "dynamic_reconfigure" "eigen" "message_filters" "nodelet" "nodelet_topic_tools" "libpcl-all" "libpcl-all-dev" "pcl_conversions" "pcl_msgs" "pluginlib" "rosbag" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(autonomos_gazebo_TEST_DEPENDS )
set(autonomos_gazebo_DOC_DEPENDS )
set(autonomos_gazebo_URL_WEBSITE "")
set(autonomos_gazebo_URL_BUGTRACKER "")
set(autonomos_gazebo_URL_REPOSITORY "")
set(autonomos_gazebo_DEPRECATED "")